version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - exhaustruct_v5
    - gomodguard
    - noinlineerr
    - paralleltest
    - testpackage
    - godoclint
    - ireturn
    - varnamelen
    - wsl
  settings:
    revive:
      rules:
        - name: redefines-builtin-id
          disabled: true
        - name: exported
          disabled: true
        - name: unused-parameter
        - name: unused-receiver
    tagliatelle:
      case:
        rules:
          json: snake
  exclusions:
    rules:
      - path: _test\.go$
        linters:
          - err113
          - varnamelen
          - funlen
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
    - golines
