---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      bump_type:
        type: choice
        description: "Version bump type"
        default: auto
        options: [auto, patch, minor, major]

permissions: {}

jobs:
  hk:
    uses: hugoh/go-tools/.github/workflows/go-hk.yml@4647ff119a5c7a1a92035bc3f7bc6824d89049e0
    permissions:
      contents: read

  goci:
    uses: hugoh/go-tools/.github/workflows/go-ci.yml@4647ff119a5c7a1a92035bc3f7bc6824d89049e0
    permissions:
      contents: read

  release:
    needs: [hk, goci]
    uses: hugoh/go-tools/.github/workflows/go-release.yml@4647ff119a5c7a1a92035bc3f7bc6824d89049e0
    permissions:
      contents: write
    with:
      bump_type: ${{ inputs.bump_type || 'auto' }}
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      tap_github_token: ${{ secrets.TAP_GITHUB_TOKEN }}
