---
name: Update from go-tools template

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch: {}

permissions: {}

jobs:
  update:
    uses: hugoh/go-tools/.github/workflows/go-template-update.yml@2c9827ab739a74122969fd7c0782f0a1c9c03b01
    permissions:
      contents: write
      pull-requests: write
    secrets:
      gh_token: ${{ secrets.TEMPLATE_UPDATE_TOKEN }}
